### ISSUE TITLE
[FEATURE] Allow continuation of stopped `musdb.run`

### ISSUE THREAD

**Issue by TE-StefanUhlich** [sigsep/sigsep-mus-db#12]
It would be great to have a `continued_run=True` flag for `musdb.run`, which allows to continue a previously stopped separation run (e.g., due to out-of-memory on the GPU :) )

It should check whether the WAVs have already been created and - if they already exist - the song should be skipped.

**Comment by faroit** [comment]
I added this feature in #13. Feel free to test it and tell me if thats what you suggested

**Comment by faroit** [comment]
The new musdb 0.3.0 deprecates the `.run` method, since not many people used it. We therefore can't implement this feature
