### ISSUE TITLE
Docstrings mention "Dev" and "Train" subsets but code seems to assume subsets are "train" and "test"

### ISSUE THREAD

**Issue by carlthome** [sigsep/sigsep-mus-db#3]
I just downloaded MUSDB18 and unzipped the mp4 files, and set the environment variable MUSDB_PATH to that directory. When using the Python API, `mus.load_mus_tracks('Dev')` results in an empty list, but `mus.load_mus_tracks('train')` works fine. Same problem applies to `mus.run`.

Similarly, `'Test'` has to be lowercase, it seems.

**Comment by faroit** [comment]
ooops, yes, I, forgot to update the documentation

**Comment by faroit** [comment]
fixed in 6327403
