### ISSUE TITLE
Missing link to paper

### ISSUE THREAD

**Issue by JoshuaStorm** [sigsep/sigsep-mus-db#37]
https://github.com/sigsep/sigsep-mus-db/blob/master/docs/index.rst states "If you use this package, please reference the following paper" but does not follow that with a link or paper title. I'm assuming it should be linking to: https://arxiv.org/abs/1804.06267

If this is the case, I've opened #36 to resolve

**Comment by faroit** [comment]
Sorry for not responding. Thanks a lot for spotting this. I am actually not sure which paper to cite here.  Maybe it's best to add another zenodo reference just for the tool for better reproducibility. 

Ping @aliutkus

**Comment by faroit** [comment]
resolved via better readme
