### ISSUE TITLE
got error musdb has no attribute run.

### ISSUE THREAD

**Issue by jcthink** [sigsep/sigsep-mus-db#59]
got error musdb has no attribute run.

**Comment by aliutkus** [comment]
I believe the `run` function was removed due to its rigidity.

The adequate way to now run sum function over the whole database is now simply to iterate over the tracks.
For instance:
```python
    # initiate musdb
    mus = musdb.DB(subsets="test")

    result_dir = '.'

    for track in mus:
        print(track.name)
        estimates = my_function(track)
        mus.save_estimates(estimates, track, result_dir)
```

Dos it solve the issue ?

**Comment by faroit** [comment]
@jcthink can we close this issue?
