### ISSUE TITLE
Validation tracks include test tracks when `subsets` is not specified

### ISSUE THREAD

**Issue by faroit** [sigsep/sigsep-mus-db#60]
In the readme, we state that:

`musdb.DB(subsets='train', split='valid')`

return the 14 validation tracks

However, when users do not specify subsets:

`musdb.DB(split='valid')`

 the default is used (`['train', 'test']`) and 64 tracks are returned: 50+14.
While the output is technically correct, I think for this case we should:

* raise an assertion or
* print a warning or
* assume that test has no splits so we just output the 14 valid tracks

This issue might be critical since some users might already have been using musdb that way, so that validation tracks include test tracks.

@aliutkus @TE-StefanUhlich do you have some opinion how to address this?

**Comment by faroit** [comment]
ping @TE-StefanUhlich

**Comment by TE-StefanUhlich** [comment]
Actually, it would be more intuitive if there would be only a `subsets` argument which can take three different values:
* `train`: Returns the 86 training songs (all songs from `train` which are not in `valid`)
* `valid`: Returns the 14 validation songs (from the `valid` split of `train`)
* `test`: Returns the 50 test songs

But this is also somehow confusing as the original MUSDB18 only consists of two subsets (`train` and `test`). Hence, I would vote for raising a value error and say that `split` can only be set if `split` is `train`.

**Comment by faroit** [comment]
@TE-StefanUhlich okay, I also like this one best. will do that. thanks

**Comment by faroit** [comment]
Fixed in #75
