### ISSUE TITLE
There are some updates in module but not match with dataset. 

### ISSUE THREAD

**Issue by ZyUestc** [sigsep/sigsep-mus-db#61]
Run following code:
```
import musdb 
mus_train = musdb.DB(musdb_path, subsets='train') 
L = len(mus_train)
```
The value of  L used to be 100 but 600 now.

But i do not find new dataset in [MUSDB](https://sigsep.github.io/musdb).

I also tried install past version 0.3.0, but L is 600 too.  So I can not use musdb module now. Please fix it ASAP, thanks :)

**Comment by faroit** [comment]
I cannot reproduce this. See a colab test I just did a few minutes ago: https://colab.research.google.com/drive/1GdT0N42J4kU2CSU1fAx-kYdvSjsMGKdT

Please check your `musdb_path` if you accidentally copied other folders into `train` subdirectory

**Comment by ZyUestc** [comment]
Thanks for your reply!  I have found where the problem is actually.

I found a hidden folder .@__thumb, files in this folder have almost same name to files in 'train'  except redundant prefix such as 'a000'. 

I remove that folder and L becomes back to 100.  So any idea about '.@__thumb'  folder?

**Comment by faroit** [comment]
> I remove that folder and L becomes back to 100. So any idea about '.@__thumb' folder?

this seem to have been added you your QNAP NAS storage device. If you find a way to reliably identify them, let me know so that we can add some code here. Otherwise this can be closed

**Comment by ZyUestc** [comment]
How about ignore @__thumb folder manually?
