### ISSUE TITLE
Service temporarily unavailable when downloading MUSDB

### ISSUE THREAD

**Issue by pseeth** [sigsep/sigsep-mus-db#63]
It seems that I'm getting an issue causing tests to fail where I can't download MUSDB's 7s sample dataset. Should I be hosting the MUSDB dataset somewhere else? Is this sort of use of the 7s samples not viable? Here's the failure:

https://github.com/nussl/nussl/runs/591200479#step:7:51

**Comment by pseeth** [comment]
Ah, Zenodo is down for maintenence, I guess? 

>We'll be back soon.
>
>The service will be unavailable on Thursday 16th from 07:00-10:00AM CET, due to an upgrade on our underlying storage cluster.
>
>Thank you for your patience.

**Comment by faroit** [comment]
ah yes, right, they do this from time to time. Not nice for unit tests but still better than pay for AWS ;-)
