### ISSUE TITLE
mismatch with latest beta `stempeg`

### ISSUE THREAD

**Issue by aliutkus** [sigsep/sigsep-mus-db#65]
due to a change of variable names in `stempeg`
* https://github.com/sigsep/sigsep-mus-db/blob/869b51f4c2acb1e9c531921b8066ba377e65ff33/musdb/audio_classes.py#L56 doesn't work. Should be `sample_rate`
* what about https://github.com/sigsep/sigsep-mus-db/blob/869b51f4c2acb1e9c531921b8066ba377e65ff33/musdb/audio_classes.py#L61 ?

**Comment by faroit** [comment]
https://github.com/faroit/stempeg/pull/28 is an unpublished branch so for now this is not an issue.
