### ISSUE TITLE
Is MUSDB18 bandwidth really 16 kHz?

### ISSUE THREAD

**Issue by fxmarty** [sigsep/sigsep-mus-db#69]
Hello,

This issue is not directly related to sigsep-mus-db repo, but I was thinking maybe @faroit or @aliutkus may give additional information on this.

After getting MUSDB18 dataset from a colleague, and plotting stft for some samples of the tracks, I get for example this:

![spec](https://user-images.githubusercontent.com/9808326/90516165-e8162a00-e163-11ea-9d66-2d3b065f50c9.png)

![Screenshot_20200818_150320](https://user-images.githubusercontent.com/9808326/90516212-f9f7cd00-e163-11ea-870c-3a9247dae9ed.png)

Or after converting to wav with musdbconvert:

![Screenshot_20200818_150543](https://user-images.githubusercontent.com/9808326/90516460-4e02b180-e164-11ea-9c23-2b7dadd9b773.png)

On these examples, the bandwidth seem to be 17 kHz and not 16 kHz as indicated on https://sigsep.github.io/datasets/musdb.html . Is it that the MUSDB18 dataset I got not the original one, or is there an other explanation?

I was also wondering why would we keep MUSDB18 sampled at 44.1 kHz and not simply at 32 kHz (if the bandwidth is 16 kHz).

Thank you!

Félix

**Comment by faroit** [comment]
Hi, thanks for your feedback. I guess you are right and AAC can have up to 17 Khz. We might want to change the documentation...

Concerning the default sample rate: we wanted to use the stem format which only supports 44k as far as I know.
