### ISSUE TITLE
"ffmpeg or ffprobe could not be found!"

### ISSUE THREAD

**Issue by YadChen** [sigsep/sigsep-mus-db#74]
After I installed the 0.1.8 Version of the Stempeg package,  I used the Conda directive to install the 4.3.1 Ffmpeg package and the 0.5.0 version of the FFProbe package. However,  When I used import Stempeg in Pycharm,  I got the following error:

File "/home3/chenYD/code/Wave-U-Net-Pytorch-master/1.py", line 1, in <module>
    import stempeg
  File "/home3/chenYD/anaconda3/lib/python3.7/site-packages/stempeg/__init__.py", line 34, in <module>
    raise RuntimeError('ffmpeg or ffprobe could not be found! '
RuntimeError: ffmpeg or ffprobe could not be found! Please install them before using stempeg. See: https://github.com/faroit/stempeg

**Comment by faroit** [comment]
Can you check your command line within the pycharm environment if you can access ffmpeg? If not it's probably a pycharm problem

**Comment by YadChen** [comment]
> Can you check your command line within the pycharm environment if you can access ffmpeg? If not it's probably a pycharm problem

Thanks for your response. I tried to use "import ffmpeg" in Pycharm, but I got the following error message:

Traceback (most recent call last):
  File "/home3/chenYD/code/Wave-U-Net-Pytorch-master/1.py", line 1, in <module>
    import ffmpeg
ModuleNotFoundError: No module named 'ffmpeg'

Process finished with exit code 1

But interestingly, I had already installed the ffmpeg package before, and in the shell when I looked at the installed package I found that ffmpeg exists, do you know why?

**Comment by faroit** [comment]
> Thanks for your response. I tried to use "import ffmpeg" in Pycharm, but I got the following error message:

ffmpeg is not a python package so you have to test this from the bash within your IDE

**Comment by YadChen** [comment]
> > Thanks for your response. I tried to use "import ffmpeg" in Pycharm, but I got the following error message:
> 
> ffmpeg is not a python package so you have to test this from the bash within your IDE

When I tried to use the "ffmpeg.exe" command to complete some operations in the command line,  it could not succeed, error message:" ffmpeg. exe: Command not found".
What is the reason for this?
Before this, I found the installation information of the ffmpeg in its official website, and in the Linux environment has been successfully installed ffmpeg, environment variables have also been configured.
But that doesn't work...

**Comment by faroit** [comment]
> When I tried to use the "ffmpeg.exe" command to complete some operations in the command line, it could not succeed, error message:" ffmpeg. exe: Command not found".
What is the reason for this?

I guess you would have to figure out how to correctly install ffmpeg with conda and activate this environment from within your IDE. This is out of scope of this project as I can't give support for pycharm or conda.

Feel free to reopen this issue when you think its related to this repo
