### ISSUE TITLE
Module 'musdb' has no attribute 'DB'

### ISSUE THREAD

**Issue by wh1tePigeon** [sigsep/sigsep-mus-db#81]
I have installed musdb using pip, but when i run this code:

```
def main():
    import musdb
    mus = musdb.DB(download=True)
    for track in mus:
        print(track.name)


if __name__ == "__main__":
    main()
```

I get **AttributeError: module 'musdb' has no attribute 'DB'** I`ve tried reinstalling musdb using pip but it didn't help.

**Comment by wh1tePigeon** [comment]
Nvm, I`ve created new environment, it helped

**Comment by faroit** [comment]
Good to hear it works
